apiVersion: v1
kind: Service
metadata:
    name: "assentify-0a42"
    labels:
        app: "assentify-0a42"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "assentify-0a42"